# Generated by Django 5.2.4 on 2025-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('semester_number', models.IntegerField()),
                ('student_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoreCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('is_lab', models.BooleanField()),
                ('duration', models.IntegerField(default=75)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('is_tech', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('section_name', models.CharField(max_length=10)),
                ('number_of_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='title',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='cohort_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='core_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='dld',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='data',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
