# Generated by Django 4.2.7 on 2025-07-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_enhancedschedule_schedulingconstraint_and_more'),
        ('main', '0004_add_enhanced_models'),
    ]

    operations = [
    ]
