# Generated by Django 4.2.7 on 2025-07-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20250722_0136'),
        ('main', 'xxxx_lab_splitting_update'),
    ]

    operations = [
    ]
