# Generated by Django 4.2.7 on 2025-07-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20250728_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohortcourse',
            options={'verbose_name': 'Cohort Course', 'verbose_name_plural': 'Cohort Courses'},
        ),
        migrations.RemoveField(
            model_name='cohortcourse',
            name='student_range',
        ),
        migrations.AddField(
            model_name='cohortcourse',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='cohortcourse',
            name='duration',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='cohortcourse',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
    ]
